sudo: required
services:
  - docker

before_install:
  - docker build -t tanmaymohapatra/docker-react -f Dockerfile.dev .

script:
  - docker run tanmaymohapatra/docker-react npm run test -- --coverage