sudo: required
services:
  - docker

before_install:
  - docker build -t tanmaymohapatra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tanmaymohapatra/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-770225308757"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
  secret_access_key: ${{ secrets.AWS_SECRET_KEY }}